web:
  image: ubuntudesign/canonicalwebsite_web:master
  volumes:
    - .:/app
  ports:
    - "8001:5000"

npm:
  image: library/node
  working_dir: /app
  volumes_from:
    - web
  command: sh -c 'npm install'

sass:
  image: ubuntudesign/sass
  volumes_from:
    - web
  command: bash -c 'inotifywait -q -e create /app && sass --debug-info --update /app/static/css --force -E "UTF-8" && sass --debug-info --watch /app/static/css -E "UTF-8"'
