web:
  image: ubuntudesign/canonicalwebsite_web:master
  volumes:
    - .:/app
  ports:
    - "8002:5000"

npm:
  image: library/node
  working_dir: /app
  volumes_from:
    - web
  command: npm install

sass:
  image: ubuntudesign/sass
  working_dir: /app
  volumes_from:
    - web
  command: bash -c '[[ -d node_modules ]] || inotifywait -q -e create . && sass --debug-info --update static/css --force -E "UTF-8" && sass --debug-info --watch static/css -E "UTF-8"'
